=== jQAssistant/jqassistant/core/schemata/src/main/resources/META-INF/rule/xsd/jqassistant-rule-v1.10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://schema.jqassistant.org/rule/v1.10"
           targetNamespace="http://schema.jqassistant.org/rule/v1.10"
           elementFormDefault="qualified">

    <xs:element name="jqassistant-rules">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="concept" type="tns:conceptType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="constraint" type="tns:constraintType" minOccurs="0"
                            maxOccurs="unbounded"/>
                <xs:element name="group" type="tns:groupType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="referenceableType" abstract="true">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="sourceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="language" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="parameterType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="tns:parameterTypes" use="required"/>
        <xs:attribute name="defaultValue" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="parameterTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="char"/>
            <xs:enumeration value="byte"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="String"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="propertyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="severityEnumType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blocker"/>
            <xs:enumeration value="critical"/>
            <xs:enumeration value="major"/>
            <xs:enumeration value="minor"/>
            <xs:enumeration value="info"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="referenceType">
        <xs:attribute name="refId" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="optionalReferenceType">
        <xs:complexContent>
            <xs:extension base="tns:referenceType">
                <xs:attribute name="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="includedReferenceType">
        <xs:complexContent>
            <xs:extension base="tns:referenceType">
                <xs:attribute name="severity" type="tns:severityEnumType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="verificationType">
        <xs:choice>
            <xs:element name="rowCount" type="tns:rowCountVerificationType"/>
            <xs:element name="aggregation" type="tns:aggregationVerificationType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="rowCountVerificationType">
        <xs:attribute name="min" type="xs:int"/>
        <xs:attribute name="max" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="aggregationVerificationType">
        <xs:attribute name="column" type="xs:string"/>
        <xs:attribute name="min" type="xs:int"/>
        <xs:attribute name="max" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="severityRuleType" abstract="true">
        <xs:complexContent>
            <xs:extension base="tns:referenceableType">
                <xs:attribute name="severity" type="tns:severityEnumType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="executableRuleType" abstract="true">
        <xs:complexContent>
            <xs:extension base="tns:severityRuleType">
                <xs:sequence>
                    <xs:element name="requiresConcept" type="tns:optionalReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="requiresParameter" type="tns:parameterType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="description" type="xs:string" minOccurs="0"/>
                    <xs:element name="deprecated" type="xs:string" minOccurs="0"/>
                    <xs:choice>
                        <xs:element name="source" type="tns:sourceType"/>
                        <xs:element name="cypher" type="xs:string"/>
                        <xs:element name="script" type="tns:sourceType"/>
                    </xs:choice>
                    <xs:element name="verify" type="tns:verificationType" minOccurs="0"/>
                    <xs:element name="report" type="tns:reportType" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="conceptType">
        <xs:complexContent>
            <xs:extension base="tns:executableRuleType">
                <xs:sequence>
                    <xs:element name="providesConcept" type="tns:referenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="constraintType">
        <xs:complexContent>
            <xs:extension base="tns:executableRuleType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="tns:severityRuleType">
                <xs:sequence>
                    <xs:element name="includeConcept" type="tns:includedReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="includeConstraint" type="tns:includedReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="includeGroup" type="tns:includedReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="reportType">
        <xs:sequence>
            <xs:element name="property" type="tns:propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="primaryColumn" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== jQAssistant/jqassistant/core/rule/src/test/resources/executables.xml
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v1.10"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v1.10 http://schema.jqassistant.org/rule/jqassistant-rule-v1.10.xsd">

    <concept id="test:CypherConcept">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <cypher><![CDATA[
            Cypher Concept
        ]]></cypher>
    </concept>

    <concept id="test:ScriptConcept">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <script language="javascript"><![CDATA[
            Script Concept
        ]]></script>
    </concept>

    <concept id="test:SourceConcept">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="cypher"><![CDATA[
          Source Concept
        ]]></source>
    </concept>

    <concept id="test:SourceConceptUpperCase">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="CYPHER"><![CDATA[
          Source Concept (upper case)
        ]]></source>
    </concept>


    <constraint id="test:CypherConstraint">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <cypher><![CDATA[
            Cypher Constraint
        ]]></cypher>
    </constraint>

    <constraint id="test:ScriptConstraint">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <script language="javascript"><![CDATA[
            Script Constraint
        ]]></script>
    </constraint>

    <constraint id="test:SourceConstraint">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="cypher"><![CDATA[
            Source Constraint
        ]]></source>
    </constraint>

    <constraint id="test:SourceConstraintUpperCase">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="CYPHER"><![CDATA[
            Source Constraint (upper case)
        ]]></source>
    </constraint>

</jqassistant-rules>

=== jQAssistant/jqassistant/plugin/java/src/it/jpms/jqassistant/it.xml
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v1.10"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v1.10 http://schema.jqassistant.org/rule/jqassistant-rule-v1.10.xsd">

    <group id="it">
        <includeConcept refId="it:*" severity="blocker" />
    </group>

    <concept id="it:Module1AnnotatedByDeprecated">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (module1)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(:Type{fqn:"java.lang.Deprecated"})
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1RequiresJacksonCore">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (jacksonCore:Artifact{name:"jackson-core"}),
              (jacksonCore)-[:CONTAINS]->(module2:Java:Module{fqn:"com.fasterxml.jackson.core"}),
              (module1)-[:REQUIRES]->(module2)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ExportsApiPackage">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(api:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api"}),
              (module1)-[:EXPORTS]->(exportedPackage:Java:ExportedPackage),
              (exportedPackage)-[:OF_PACKAGE]->(api)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ExportsImplPackageToModule2">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(impl:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl"}),
              (module1)-[:EXPORTS]->(exportedPackage:Java:ExportedPackage),
              (exportedPackage)-[:OF_PACKAGE]->(impl),
              (exportedPackage)-[:TO_MODULE]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (artifact1)-[:REQUIRES]->(module2)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1OpensApiPackage">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(api:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api"}),
              (module1)-[:OPENS]->(openPackage:Java:OpenPackage),
              (openPackage)-[:OF_PACKAGE]->(api)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1OpensImplPackageToModule2">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(impl:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl"}),
              (module1)-[:OPENS]->(openPackage:Java:OpenPackage),
              (openPackage)-[:OF_PACKAGE]->(impl),
              (openPackage)-[:TO_MODULE]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (artifact1)-[:REQUIRES]->(module2)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ProvidesService">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(serviceType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api.MyService"}),
              (artifact1)-[:CONTAINS]->(providerType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl.MyServiceImpl"}),
              (module1)-[:PROVIDES]->(providedService:Java:ProvidedService),
              (providedService)-[:OF_TYPE]->(serviceType),
              (providedService)-[:WITH_PROVIDER]->(providerType)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ProvidesInnerService">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(serviceType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api.MyService$InnerService"}),
              (artifact1)-[:CONTAINS]->(providerType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl.MyServiceImpl$InnerServiceImpl"}),
              (module1)-[:PROVIDES]->(providedService:Java:ProvidedService),
              (providedService)-[:OF_TYPE]->(serviceType),
              (providedService)-[:WITH_PROVIDER]->(providerType)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module2UsesService">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (module1)-[:PROVIDES]->(providedService:Java:ProvidedService)-[:OF_TYPE]->(serviceType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api.MyService"}),
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (module2)-[:USES]->(serviceType)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module2RequiresModule1">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (module2)-[:REQUIRES]->(module1)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:OpenModule2">
        <cypher><![CDATA[
            MATCH
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2", open:true})
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module2RequiresStaticTransitiveModuleJavaSE">
        <cypher><![CDATA[
            MATCH
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (module2)-[:REQUIRES{static:true, transitive:true}]->(:Java:Module{fqn:"java.se"})
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

</jqassistant-rules>

=== jQAssistant/jqassistant/plugin/junit/src/main/resources/META-INF/jqassistant-rules/junit-common.xml
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v1.10"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v1.10 http://schema.jqassistant.org/rule/jqassistant-rule-v1.10.xsd">

<group id="junit:Default">
        <includeConstraint refId="junit:IgnoreWithoutMessage"/>
    </group>

    <concept id="junit:TestCaseDefinedByClass">
        <description>Creates a relation DEFINED_BY between all test cases from test reports and the class which defined it.</description>
        <cypher><![CDATA[
            MATCH
              (testcase:TestCase)
            WITH
              testcase
            MATCH
              (testclass:Type)
            WHERE
              testclass.fqn = testcase.className
            MERGE
              (testcase)-[:DEFINED_BY]->(testclass)
            RETURN
              testcase.name AS TestCase, testclass AS TestClass
    ]]></cypher>
    </concept>

    <concept id="junit:TestCaseImplementedByMethod">
        <requiresConcept refId="junit:TestCaseDefinedByClass" />
        <description>Creates a relation IMPLEMENTED_BY between all test cases from test reports and their implementing
            methods.
        </description>
        <cypher><![CDATA[
            MATCH
              (testcase:TestCase)-[:DEFINED_BY]->(testclass:Type),
              (testclass)-[:EXTENDS*0..]->(:Type)-[:DECLARES]->(testmethod:Method)
            WHERE
              testmethod.name = testcase.name
            MERGE
              (testcase)-[:IMPLEMENTED_BY]->(testmethod)
            RETURN
              testcase.name AS TestCase, testmethod as TestMethod
    ]]></cypher>
    </concept>

    <concept id="junit:Inactive">
        <description>Abstract concept returning all elements labeled with :JUnit:Inactive and the according reason.</description>
        <cypher><![CDATA[
            MATCH
              (t:Type)-[:DECLARES*0..1]->(e:JUnit:Inactive)
            RETURN
               t AS DeclaringType, e AS Element, e.inactiveReason AS Reason
    ]]></cypher>
    </concept>

    <concept id="junit:Disabled">
        <providesConcept refId="junit:Inactive" />
        <description>Concept labeling all @Disabled-annotated elements with :JUnit:Inactive and setting the according reason.</description>
        <cypher><![CDATA[
            MATCH
              (t:Type)-[:DECLARES*0..1]->(e),
              (e)-[:ANNOTATED_BY]->(disabled:Annotation)-[:OF_TYPE]->(ignoreType:Type {fqn: "org.junit.jupiter.api.Disabled"})
            OPTIONAL MATCH
              (disabled)-[:HAS]->(value:Value {name:"value"})
            SET
              e:JUnit:Inactive,
              e.inactiveReason = value.value
            RETURN
              t AS DeclaringType, e AS Element, e.inactiveReason AS Reason
    ]]></cypher>
    </concept>

    <concept id="junit:Ignore">
        <providesConcept refId="junit:Inactive" />
        <description>Concept labeling all @Ignore-annotated elements with :JUnit:Inactive and setting the according reason.</description>
        <cypher><![CDATA[
            MATCH
              (t:Type)-[:DECLARES*0..1]->(e),
              (e)-[:ANNOTATED_BY]->(disabled:Annotation)-[:OF_TYPE]->(ignoreType:Type {fqn: "org.junit.Ignore"})
            OPTIONAL MATCH
              (disabled)-[:HAS]->(value:Value {name:"value"})
            SET
              e:JUnit:Inactive,
              e.inactiveReason = value.value
            RETURN
              t AS DeclaringType, e AS Element, e.inactiveReason AS Reason
    ]]></cypher>
    </concept>

    <constraint id="junit:IgnoreWithoutMessage">
        <requiresConcept refId="junit:Inactive" />
        <description>Inactive tests must be provided with an according reason.</description>
        <cypher><![CDATA[
            MATCH
              (t:Type)-[:DECLARES*0..1]->(e:Inactive)
            WHERE
              e.inactiveReason IS NULL
            RETURN
              t AS DeclaringClass, e AS IgnoreWithoutMessage
        ]]></cypher>
        <report primaryColumn="IgnoreWithoutMessage"/>
    </constraint>
</jqassistant-rules>
